fix

diff --git a/zulip_za_sirotinju_fe/Dockerfile b/zulip_za_sirotinju_fe/Dockerfile
--- a/zulip_za_sirotinju_fe/Dockerfile
+++ b/zulip_za_sirotinju_fe/Dockerfile
@@ -3,27 +3,25 @@ FROM node:18-alpine AS base
 
 ARG next_public_graphql
 ARG nextauth_secret
+ARG ws_link
+ARG nextauth_url
 
 ENV NEXT_PUBLIC_GRAPHQL=$next_public_graphql
 ENV NEXTAUTH_SECRET=$nextauth_secret
+ENV WS_LINK=$ws_link
+ENV NEXTAUTH_URL=$nextauth_url
 
-# Install dependencies only when needed
 FROM base AS deps
-# Check https://github.com/nodejs/docker-node/tree/b4117f9333da4138b03a546ec926ef50a31506c3#nodealpine to understand why libc6-compat might be needed.
 RUN apk add --no-cache libc6-compat
 WORKDIR /app
 
-# Install dependencies based on the preferred package manager
-# COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml* ./
-# RUN \
-#   if [ -f yarn.lock ]; then yarn --frozen-lockfile; \
-#   elif [ -f package-lock.json ]; then npm ci; \
-#   elif [ -f pnpm-lock.yaml ]; then yarn global add pnpm && pnpm i --frozen-lockfile; \
-#   else echo "Lockfile not found." && exit 1; \
-#   fi
-
-COPY package.json ./
-RUN yarn global add pnpm && pnpm i
+COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml* ./
+RUN \
+  if [ -f yarn.lock ]; then yarn --frozen-lockfile; \
+  elif [ -f package-lock.json ]; then npm ci; \
+  elif [ -f pnpm-lock.yaml ]; then yarn global add pnpm && pnpm i --frozen-lockfile; \
+  else echo "Lockfile not found." && exit 1; \
+  fi
 
 
 # Rebuild the source code only when needed
@@ -37,7 +35,7 @@ COPY . .
 # Uncomment the following line in case you want to disable telemetry during the build.
 # ENV NEXT_TELEMETRY_DISABLED 1
 
-RUN yarn global add pnpm && pnpm build 
+RUN yarn build
 
 # If using npm comment out above and use below instead
 # RUN npm run build
@@ -55,6 +53,8 @@ RUN adduser --system --uid 1001 nextjs
 
 COPY --from=builder /app/public ./public
 
+# Automatically leverage output traces to reduce image size
+# https://nextjs.org/docs/advanced-features/output-file-tracing
 COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
 COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static
 
